[phases.setup]
nixPkgs = ["chromium", "nodejs"]

[phases.build]
cmds = ["npm install", "npm run build", "cd backend && npm install", "which chromium > /app/chromium-path.txt"]

[start]
cmd = "bash -c 'export PUPPETEER_EXECUTABLE_PATH=$(cat /app/chromium-path.txt); cd /app/backend && node src/server.js'"
