[phases.setup]
nixPkgs = ["chromium", "nodejs"]

[phases.build]
cmds = ["npm install", "npm run build", "cd backend && npm install"]

[start]
cmd = "cd backend && PUPPETEER_EXECUTABLE_PATH=$(which chromium) node src/server.js"
